### ISSUE TITLE
Not able to sudo to root

### ISSUE THREAD

**Issue by jasonchambers31** [kodekloudhub/kodekloud-engineer#11]
Hi! I am new to kodekloud engineer.

   On my first task to complete I need to disable root from being able to ssh between servers. Ansible is available to use, but I was not able to sudo to root even though thor has wheel privileges.
Also, I was not able to ssh from the jump_host as thor to Nautilus Mail Server and Nautilus App 1. 

Am I supposed to use my kodekloud engineer login password for this?

Thank you,
Jason

**Comment by jasonchambers31** [comment]
Nevermind... I found the passwords on the dashboard.
https://kodekloudhub.github.io/kodekloud-engineer/docs/projects/nautilus

**Comment by jasonchambers31** [comment]
I was able to sudo to root, but still cannot ssh to Nautilus Mail Server and Nautilus App 1. 
I tried: ssh thor@IP and ssh thor@hostname on both servers. 
I noticed the user ansible, but could not find any other related files.
Am I supposed to install Ansible on the server, create a playbook and script to fix this issue? 
Thank you...

**Comment by bryanasdev000** [comment]
> I was able to sudo to root, but still cannot ssh to Nautilus Mail Server and Nautilus App 1.
> I tried: ssh thor@IP and ssh thor@hostname on both servers.
> I noticed the user ansible, but could not find any other related files.
> Am I supposed to install Ansible on the server, create a playbook and script to fix this issue?
> Thank you...

 Hi @jasonchambers31 !
I don't know what task you are on, but AFAIK you need to SSH into the desired machine by IP.

**Comment by Tej-Singh-Rana** [comment]
I am closing this issue.
If you encounter any issues related to the KKE, please create a new issue.
Queries related to the KKE tasks, please ask in the link below: -
https://community.kodekloud.com/c/kodekloud-engineer/

Regards,
KodeKloud Team
