### ISSUE TITLE
Troubleshoot or configure Haproxy on Nautilus HTTP LBR?

### ISSUE THREAD

**Issue by patridas20** [kodekloudhub/kodekloud-engineer#12]
Hi,
 Please I am a new student on this platform. The question about Haproxy is so clear to me. I checked the configuration but nothing is inside. Therefore I don't know what you mean by asking for troubleshooting Haproxy in Nautilus HTTP LBR. By the end, I like this plateform . Thanks

Question on: https://github.com/kodekloudhub/kodekloud-engineer/tree/master/_docs/projects/nautilus.md

**Comment by iamfredrickokereke** [comment]
Hello, @patridas20 Haproxy is an open-source software service that helps to avoid overload of a resource(s), it acts as a load balancer.   

The Task requires this service to be running, hence to confirm you must check the configuration file using (sudo vi /etc/haproxy/haproxy.cfg), For starters, you need to check the file and correct typos, then restart the service (sudo systemctl restart haproxy) and then check the service status (sudo systemctl status haproxy).

I also will suggest you check the KK community as there are ample clarifications by other Engineers.

Best Wishes.

**Comment by iamfredrickokereke** [comment]
Hope this helps too - https://www.digitalocean.com/community/tutorial_series/common-haproxy-errors

**Comment by patridas20** [comment]
Thank you for your response, it is very helpful. Are all of the kk tasks
documented like the case of HTTP LBR?
Thank you again

**Comment by Tej-Singh-Rana** [comment]
I am closing this issue.
If you encounter any issues related to the KKE, please create a new issue.
Queries related to the KKE tasks, please ask in the link below: -
https://community.kodekloud.com/c/kodekloud-engineer/

Regards,
KodeKloud Team
