### ISSUE TITLE
firewall task

### ISSUE THREAD

**Issue by Pezoambose** [kodekloudhub/kodekloud-engineer#15]
I am having a problem connecting to app1. The password for the tony user doesnt work for me. I don't know why.

**Comment by Tej-Singh-Rana** [comment]
I am closing this issue.
If you encounter any issues related to the KKE, please create a new issue.
Queries related to the KKE tasks, please ask in the link below: -
https://community.kodekloud.com/c/kodekloud-engineer/

Regards,
KodeKloud Team
