### ISSUE TITLE
permission denied error

### ISSUE THREAD

**Issue by devenm20** [kodekloudhub/kodekloud-engineer#16]
I was assigned a task to create a user with non interactive shell. I tried but it shows permission denied error in terminal. I followed below steps.

ssh tony@stapp01
After login
sudo adduser mariyam -s /sbin/nologin
cd /home/mariyam
permission denied error. Please let me know if I have missed anything.

**Comment by Tej-Singh-Rana** [comment]
I am closing this issue.
If you encounter any issues related to the KKE, please create a new issue.
Queries related to the KKE tasks, please ask in the link below: -
https://community.kodekloud.com/c/kodekloud-engineer/

Regards,
KodeKloud Team
