### ISSUE TITLE
Unable to ssh into any of the servers

### ISSUE THREAD

**Issue by ram-bandaru** [kodekloudhub/kodekloud-engineer#18]
Hi, 

I'm working on the NFS troubleshooting task. The console on the jumphost wouldn't respond to any commands. I'm unable to ssh into any of the app servers or the storage server. I couldn't even list the processes to kill them. Please check. Thanks.

**Comment by Tej-Singh-Rana** [comment]
I am closing this issue.
If you encounter any issues/bugs related to the KKE, please create a new issue.
Queries related to the KKE tasks, please ask in the link below: -
https://community.kodekloud.com/c/kodekloud-engineer/

Regards,
KodeKloud Team
