### ISSUE TITLE
using the credentials  wont work 

### ISSUE THREAD

**Issue by Pickacho** [kodekloudhub/kodekloud-engineer#24]
when trying to perform the task of change and update the Message of the day.
the credentials  wont work  for the servers

**Comment by Tej-Singh-Rana** [comment]
I am closing this issue.
If you encounter any issues related to the KKE, please create a new issue.
Queries related to the KKE tasks, please ask in the link below: -
https://community.kodekloud.com/c/kodekloud-engineer/

Regards,
KodeKloud Team
