### ISSUE TITLE
User | Password | Purpose not working on all servers

### ISSUE THREAD

**Issue by Pickacho** [kodekloudhub/kodekloud-engineer#25]
Question on: https://github.com/kodekloudhub/kodekloud-engineer/tree/master/_docs/projects/nautilus.md

User | Password | Purpose not working on all servers
stapp01 | 172.16.238.10 | stapp01.stratos.xfusioncorp.com | tony | Ir0nM@n | Nautilus App 1

ssh tony@172.16.238.10

**Comment by Tej-Singh-Rana** [comment]
I am closing this issue.
If you encounter any issues related to the KKE, please create a new issue.

Queries related to the KKE tasks, please ask in the link below: -
https://community.kodekloud.com/c/kodekloud-engineer/

Regards,
KodeKloud Team

**Comment by Pickacho** [comment]
Hi @Tej-Singh-Rana 
Why are you closing the ticket?
did it work for you?

**Comment by Tej-Singh-Rana** [comment]
Hi @Pickacho ,
Yes, of course.
