### ISSUE TITLE
Unable To SSH into any of the servers. 

### ISSUE THREAD

**Issue by mhumair** [kodekloudhub/kodekloud-engineer#28]
I'm unable to ssh into any of the servers in the task  :

Linux Remote Copy
--

https://user-images.githubusercontent.com/39047231/131241750-8104ed46-36dc-4d62-b2d6-7aad28fbd840.mp4

stapp01 | 172.16.238.10 | stapp01.stratos.xfusioncorp.com | tony | Ir0nM@n | Nautilus App 1
stapp02 | 172.16.238.11 | stapp02.stratos.xfusioncorp.com | steve | Am3ric@ | Nautilus App 2
stapp03 | 172.16.238.12 | stapp03.stratos.xfusioncorp.com | banner | BigGr33n | Nautilus App 3 

Can anyone check please :pray:

**Comment by Tej-Singh-Rana** [comment]
I am closing this issue.
If you encounter any issues/bugs related to the KKE, please create a new issue.

Queries related to the KKE tasks, please ask in the link below: -
https://community.kodekloud.com/c/kodekloud-engineer/

Regards,
KodeKloud Team
