### ISSUE TITLE
Question:root password

### ISSUE THREAD

**Issue by mugirene** [kodekloudhub/kodekloud-engineer#3]
Question on: https://github.com/kodekloudhub/kodekloud-engineer/tree/master/_docs/projects/nautilus.md

**Comment by shuuji3** [comment]
Hello, mugirene

When do you need the root password? If you know the password of users who can `sudo`, you can become root by `su` command.

## Example

```shell
thor@jump_host /$ sudo su

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for thor: [enter user password here]

root@jump_host /# 
```

**Comment by banyejinghungui** [comment]
sudo works for me... Thanks @shuuji3

**Comment by Tej-Singh-Rana** [comment]
I am closing this issue. 
If you encounter any issues related to the KKE, please create a new issue. 

Regards,
KodeKloud Team
