### ISSUE TITLE
SSH is not working from Jumpbox in first assignment

### ISSUE THREAD

**Issue by ghost** [kodekloudhub/kodekloud-engineer#30]
Is there something wrong with the platform right now?

**Comment by Tej-Singh-Rana** [comment]
I am closing this issue.
If you encounter any issues related to the KKE, please create a new issue.

Queries related to the KKE tasks, please ask in the link below: -
https://community.kodekloud.com/c/kodekloud-engineer/

Regards,
KodeKloud Team
