### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by umeshauv** [kodekloudhub/kodekloud-engineer#31]
One of my tasks was reported as incomplete.  I submitted it for review, but the recording was incomplete probably because of some terminal issues.   How do you report this and also is it possible to request the same task to be assigned since it can't be reviewed ?

**Comment by Tej-Singh-Rana** [comment]
I am closing this issue.
If you encounter any issues/bugs related to the KKE site, please create a new issue.

Queries related to the KKE tasks, please ask in the link below: -
https://community.kodekloud.com/c/kodekloud-engineer/

Regards,
KodeKloud Team
