### ISSUE TITLE
Support page links to 404

### ISSUE THREAD

**Issue by cnpatric** [kodekloudhub/kodekloud-engineer#32]
Your about page links to a 404 if you click on support

https://kodekloudhub.github.io/kodekloud-engineer/about/

**Comment by Tej-Singh-Rana** [comment]
Hi @cnpatric,
Thanks for highlighting this. I forwarded this to our KKE team. They will check. 

Best Regards,
KodeKloud Team

**Comment by Tej-Singh-Rana** [comment]
This has been fixed it.
