### ISSUE TITLE
Unable to login to stapp03.stratos.xfusioncorp.com

### ISSUE THREAD

**Issue by saurabhcobra** [kodekloudhub/kodekloud-engineer#36]
ssh stapp03
The authenticity of host 'stapp03 (172.16.238.12)' can't be established.
ECDSA key fingerprint is SHA256:DerGKjH54N8cAfev03SNCUXm6AQlXClEwJUo7riU70c.
ECDSA key fingerprint is MD5:51:32:e1:af:d8:74:4c:0b:cd:fd:a8:bf:d0:e2:82:99.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'stapp03,172.16.238.12' (ECDSA) to the list of known hosts.
thor@stapp03's password: 
Permission denied, please try again.
thor@stapp03's password: 
Permission denied, please try again.

**Comment by Tej-Singh-Rana** [comment]
Hi @saurabhcobra ,
Next time, please use this method: - 
```
sshpass -p 'BigGr33n' ssh -q -o 'StrictHostKeyChecking no' banner@stapp03
```

Regards,
