### ISSUE TITLE
Password Issue

### ISSUE THREAD

**Issue by vijay213** [kodekloudhub/kodekloud-engineer#4]
While connecting to through ssh
like ssh ipaddress
asking password
if we enter password showing password error

**Comment by gokuno1** [comment]
> While connecting to through ssh
> like ssh ipaddress
> asking password
> if we enter password showing password error

Actually each server has its username and password which is provided in the documentation. 
You can use that password for ssh connection. You can also try using hostname along with IP address it helped me.
https://kodekloudhub.github.io/kodekloud-engineer/docs/projects/nautilus

**Comment by Tej-Singh-Rana** [comment]
I am closing this issue.
If you encounter any issues related to the KKE, please create a new issue.

Regards,
KodeKloud Team
