### ISSUE TITLE
Install the required packages of SElinux on App server 2 in Stratos Datacenter

### ISSUE THREAD

**Issue by Mobolaji-Ajayi** [kodekloudhub/kodekloud-engineer#6]
Hello - I'm new to this and on my first task. I can't seem to be able to change the user to steve or to root to get into stapp02 server. Thanks.

![image](https://user-images.githubusercontent.com/63762368/79760925-63ff8300-82e6-11ea-9937-9ab27a7abb74.png)

Bola

**Comment by bryanasdev000** [comment]
@Bola-Ajayi you probably need to SSH into stapp02 then use su.

**Comment by Tej-Singh-Rana** [comment]
I am closing this issue.
If you encounter any issues related to the KKE, please create a new issue.

Regards,
KodeKloud Team
