### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by hv539a** [kodekloudhub/kodekloud-engineer#7]
Question on: https://github.com/kodekloudhub/kodekloud-engineer/tree/master/_docs/projects/nautilus.md

What is the passowrd to login to root

**Comment by bryanasdev000** [comment]
> Question on: https://github.com/kodekloudhub/kodekloud-engineer/tree/master/_docs/projects/nautilus.md
> 
> What is the passowrd to login to root

Hi @hv539a ! You can login as the user in the docs then `sudo su -` to get root!

**Comment by Tej-Singh-Rana** [comment]
I am closing this issue.
If you encounter any issues related to the KKE, please create a new issue.

Regards,
KodeKloud Team
