### ISSUE TITLE
Not able to login root 

### ISSUE THREAD

**Issue by lakshitarius** [kodekloudhub/kodekloud-engineer#9]
Hi 

I am new to kodekloudEngineer.I would like to know who can help with the tasks if I dont know how to do them ?

Please let me know how can access the roor for installing software given in tasks .My password doesnt work .

**Comment by bryanasdev000** [comment]
> Hi
> 
> I am new to kodekloudEngineer.I would like to know who can help with the tasks if I dont know how to do them ?
> 
> Please let me know how can access the roor for installing software given in tasks .My password doesnt work .

Hi @lakshitarius ! The password for each machine is in the wiki.

**Comment by garfield786** [comment]
Google can help you do most of tasks, if not you can click Review at  the end of each failed attempt and someone from community will help you.
The usernames and passwords to all servers are in the wiki: https://kodekloudhub.github.io/kodekloud-engineer/docs/projects/nautilus

**Comment by Tej-Singh-Rana** [comment]
I am closing this issue.
If you encounter any issues related to the KKE, please create a new issue.
Queries related to the KKE tasks, please ask in the link below: -
https://community.kodekloud.com/c/kodekloud-engineer/

Regards,
KodeKloud Team
